name: Build and deploy app to AWS

on:
  push:
    branches:
      - test
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Install Eclipse Temurin distribution of Java
          java-version: '17'
          cache: 'maven'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Copy JAR to aws-app directory
        run: |
          cp target/*.jar aws-app/  

      - name: Zip artifact for deployment
        run: zip -r deploy.zip . -i "aws-app/*" "swag/*" "docker-compose.yaml" "target"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: |
            deploy.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: app

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: tic-tac-toe
          environment_name: tic-tac-toe-docker
          use_existing_version_if_available: true
          version_label: github-actions-${{ github.sha }}
          region: eu-north-1
          deployment_package: deploy.zip
          wait_for_deployment: false

      - name: Notify deployment success
        run: echo "Deployment to AWS Elastic Beanstalk successful!"
